# Generated by Django 3.1.4 on 2025-01-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('messages', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Connect',
            },
        ),
        migrations.CreateModel(
            name='SponsoredBlockFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name2', models.CharField(blank=True, max_length=255, null=True)),
                ('name3', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'SponsoredBlockFour',
            },
        ),
        migrations.CreateModel(
            name='SponsoredBlockThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'SponsoredBlockThree',
            },
        ),
        migrations.CreateModel(
            name='SponsoredBlockTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'SponsoredBlockTwo',
            },
        ),
        migrations.CreateModel(
            name='TabOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tab One',
            },
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'VideoLink',
            },
        ),
    ]
