# Generated by Django 4.2 on 2026-01-27 23:21

from django.db import migrations, models
import web_app.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.FileField(blank=True, null=True, upload_to='images/mapleridge', verbose_name='Image')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Video')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BTS Maple Ridge',
            },
        ),
        migrations.CreateModel(
            name='TabTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.FileField(blank=True, null=True, upload_to='images/aldergrove', verbose_name='Image')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Video')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BTS Aldergrove',
            },
        ),
        migrations.AlterModelOptions(
            name='tabone',
            options={'verbose_name_plural': 'BTS Kelowna'},
        ),
        migrations.AddField(
            model_name='tabone',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabone',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='images/kelowna', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tabone',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='videolink',
            name='background_url',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='videolink',
            name='video_url',
            field=models.FileField(blank=True, null=True, storage=web_app.azure_storage.AzureMediaStorage, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='tabone',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
